### ISSUE TITLE
sfxr.me does not play sound in Safari but original fork does

### ISSUE THREAD

**Issue by chr15m** [chr15m/jsfxr#1]
@gingerbeardman reported:

> I noticed your http://sfxr.me does not play sounds in Safari, but the original code does: http://github.grumdrig.com/jsfxr/

**Comment by chr15m** [comment]
Hey @gingerbeardman I've been investigating this and I replicated it on my device, but then I discovered I could make the sound play if I had headphones plugged in and I saw this: https://stackoverflow.com/questions/21122418/ios-webaudio-only-works-on-headphones

When I turned off the physical mute button on the side of my old iPad it started producing sounds. I can't work out if this is a bug or not.

**Comment by gingerbeardman** [comment]
How odd!

I'm using Safari on desktop macOS, but I can try with headphones later.

**Comment by chr15m** [comment]
If you can get a console log for me that would be super helpful. I only have one Apple device and it's very old.

**Comment by gingerbeardman** [comment]
Here we go!

![Screen shot 2020-07-25 at 11 03 44](https://user-images.githubusercontent.com/49612/88454306-94673800-ce66-11ea-9514-1c35a30c5b4d.png)

**Comment by gingerbeardman** [comment]
Maybe use a shim so one code path can run on all browsers?

https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Web_Audio_API_cross_browser

**Comment by chr15m** [comment]
@gingerbeardman have pushed a possible fix. Any chance you can test it?

**Comment by gingerbeardman** [comment]
Works a treat! Nicely done.

Thank you

**Comment by chr15m** [comment]
Great, thanks for testing!
