### ISSUE TITLE
Support for other output types

### ISSUE THREAD

**Issue by gingerbeardman** [chr15m/jsfxr#3]
As well as serialising, it would be great if I could get it to output directly in a format I need to use.

I am working on a game for Playdate https://play.date and can provide a template for the synth functions it uses when the time comes.

**Comment by chr15m** [comment]
You can get a raw, normalized buffer of the audio by doing `mysoundeffect.generate().generate`. If this is sufficient I will document it more clearly.

**Comment by gingerbeardman** [comment]
Don't worry.

I guide it will be easy enough for me to code a reader for the JSON, it maps pretty well anyway.

Cheers!
