### ISSUE TITLE
Middle section gets too wide and wiggles around sometimes

### ISSUE THREAD

**Issue by grumdrig** [chr15m/jsfxr#7]
You've done some great things with this project, so thanks for improving it. My one quibble is that when the Frequency Delta Slide gets too wide (too close to zero) it moves that whole section around. For some reason the numbers in my version of the app don't get so small (and therefore large because of all the leading zeros.) 

Maybe it would help to change the relevant function:

    p_freq_dramp: function (v) {
        return (v*44100 / Math.pow(2, -44101./44100)).toPrecision(4) +
    ' 8va/sec^2?'; },

by multiplying it by 1000 and expressing the units as `m8va/sec^2`? 

And/or boldly remove the question mark?

And/or changing `sec^2` to `sec<sup>2</sup>`? But that might cause other layout difficulties.

**Comment by chr15m** [comment]
Huh, I hadn't noticed that before. Thanks for the suggestions, will try them out.

Erik thanks so much for making and releasing jsfxr under a permissive license. I've had a lot of fun making weird things with it over the years like this [chiptune live-coding IDE](https://chr15m.github.io/speccy/) and [this album](https://chr15m.bandcamp.com/album/hacksilver) and I recently started working on [a chiptune tracker](https://8bitmusicmaker.com) that uses it too. Very grateful! I never would have had the patience to implement this myself. :pray:

**Comment by grumdrig** [comment]
Wow, that's a lot of great stuff. It looks like you have plenty of
patience. And all props have to go to Dr. Petter for the brilliant original.

**Comment by chr15m** [comment]
Wow it took me forever to figure out how to fix that wiggle!

**Comment by grumdrig** [comment]
Looks great, though. Thanks!
